Changes merge workflow to deploy to staging endpoint

diff --git a/.github/workflows/merge_pr.yml b/.github/workflows/merge_pr.yml
--- a/.github/workflows/merge_pr.yml
+++ b/.github/workflows/merge_pr.yml
@@ -13,16 +13,48 @@ jobs:
     steps:
       - name: 'Confirm'
         run: echo Just checking PR is merged and not closed
-  build-and-upload:
+  deploy-to-dev:
     runs-on: ubuntu-latest
     needs: [confirm-merge]
     steps:
-      - uses: actions/checkout@v4
-      - name: 'Build & deploy'
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Install Vercel CLI
+        run: npm install --global vercel@33.2.0
+
+      - name: Pull Vercel Environment Information
+        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
+
+      - name: Build Project Artifacts
         run: |
-          echo vercel build
-          echo vercel deploy --prebuilt >deployment-url.txt 2>error.txt
-          echo alias $deploymentUrl to dev.surfe.com
+          vercel build --token=${{ secrets.VERCEL_TOKEN }}
+          ls .vercel/output -la
+      - name: Deploy Project Artifacts to Vercel
+        run: |
+          vercel deploy --prebuilt --debug --token=${{ secrets.VERCEL_TOKEN }} >deployment-url.txt 2>error.txt
+          # We need the below code to alias the returned deploymentUrl into our custom dev domain
+          code=$?
+          if [ $code -eq 0 ]; then
+              # Now you can use the deployment url from stdout for the next step of your workflow
+              deploymentUrl=`cat deployment-url.txt`
+              # Here we actually do the aliasing to our staging url
+              vercel alias $deploymentUrl trunkbased-cicd-workflow-staging.vercel.app
+          else
+              # Handle the error
+              errorMessage=`cat error.txt`
+              echo "There was an error: $errorMessage"
+          fi
+  # build-and-upload:
+  #   runs-on: ubuntu-latest
+  #   needs: [confirm-merge]
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - name: 'Build & deploy'
+  #       run: |
+  #         echo vercel build
+  #         echo vercel deploy --prebuilt >deployment-url.txt 2>error.txt
+  #         echo alias $deploymentUrl to dev.surfe.com
         #We need the below code to alias the returned deploymentUrl into our custom dev domain
         #See: https://vercel.com/docs/cli/deploy#deploying-to-a-custom-domain
         
